// exporting the different routes
export const LANDING = '/';
export const HOME = '/home';
export const OPLEIDING = '/opleiding';
export const PGMTEAM = '/pgm-team';
export const STUDENT_DETAIL = '/pgm-team/student/:id';
export const PORTFOLIO = '/portfolio';
export const CASE_DETAIL = '/portfolio/:id';
export const NIEUWS = '/nieuws';
export const NIEUWS_DETAIL = '/nieuws/:id';
export const WERKPLEKLEREN = '/werkplekleren';
export const CONTACT = '/contact';
